fix some broken doc links
DuCanhGH/next-pwa pull request #98
Opened 2023-09-22 21:55 UTC by orpos

2023-09-22 21:57 UTC, orpos commented on docs/content/next-pwa/getting-started.mdx
> +- [You may want to ask user to reload when a new service worker is installed](https://github.com/DuCanhGH/next-pwa/tree/master/examples/lifecycle/components/PWALifecycle.tsx#L20-L40)
I tried looking for when it changed from the pages to the new app router of next js 

and i found a very similiar part and changed the link for that

2023-09-23 07:38 UTC, DuCanhGH requested changes

2023-09-23 07:38 UTC, DuCanhGH commented on docs/content/index.mdx
>    - [`next-sw` (not stable)](/next-sw)
```suggestion
  - [`next-sw` (not stable)](/docs/next-sw)
```
Also fix this link please :) I mean, it's most likely that noone actually clicks it, but it'd still be nice to have it fixed.

2023-09-23 10:18 UTC, merged

2023-09-23 10:18 UTC, DuCanhGH commented
Thanks!